question_data = [
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "Octopuses have three hearts and can change color to blend into their surroundings.", "answer": "True"},
    {"text": "The smell of rain is caused by a bacteria called actinomycetes.", "answer": "True"},
    {"text": "The inventor of the frisbee was turned into a frisbee after his death.", "answer": "True"},
    {"text": "The Eiffel Tower was originally built as a permanent structure.", "answer": "False"},
    {"text": "Honey never spoils because it is naturally acidic and low in water content.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "A group of flamingos is called a flamboyance.", "answer": "True"},
    {"text": "The first computer 'bug' was an actual insect stuck in a relay.", "answer": "True"},
    {"text": "Bananas are classified as berries, while strawberries are not.", "answer": "True"},
    {"text": "In Japan, it is illegal to dance after midnight in some places.", "answer": "True"},
    {"text": "The human body contains enough iron to make a 3-inch nail.", "answer": "True"},
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The planet Venus rotates clockwise, unlike most other planets in our solar system.", "answer": "True"},
    {"text": "The first email was sent in 1971.", "answer": "True"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "The shortest bone in the human body is in the ear.", "answer": "True"},
    {"text": "The inventor of the telephone, Alexander Graham Bell, never called his mother because she was deaf.", "answer": "True"},
    {"text": "The Sahara Desert is the largest desert in the world.", "answer": "False"},
    {"text": "A blue whale’s heart can weigh as much as a car.", "answer": "True"},
    {"text": "In Switzerland, it is illegal to own just one guinea pig because they get lonely.", "answer": "True"},
    {"text": "The first computer mouse was made of plastic.", "answer": "False"},
    {"text": "A single lightning bolt has enough energy to toast 100,000 slices of bread.", "answer": "True"},
    {"text": "The shortest country name is Chad.", "answer": "True"},
    {"text": "Polar bears have black skin under their white fur.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"text": "A snail can sleep for up to three years.", "answer": "True"},
    {"text": "The first Olympic Games took place in Greece over 2,700 years ago.", "answer": "True"},
    {"text": "The human nose can detect over 1 trillion different scents.", "answer": "True"},
    {"text": "In Florida, it is illegal to sing in a swimsuit in public.", "answer": "True"},
    {"text": "The shortest river in the world is over 100 miles long.", "answer": "False"},
    {"text": "A jellyfish is 95% water.", "answer": "True"},
    {"text": "The inventor of the light bulb was Thomas Edison.", "answer": "False"},
    {"text": "A group of owls is called a parliament.", "answer": "True"},
    {"text": "The first video uploaded to YouTube was about a zoo visit.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "In Iceland, it is illegal to kill a puffin.", "answer": "True"},
    {"text": "The shortest day of the year is called the winter equinox.", "answer": "False"},
    {"text": "A crocodile cannot stick out its tongue.", "answer": "True"}
]
